# Generated by Django 5.2 on 2025-06-08 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tajriba', models.IntegerField(blank=True, null=True)),
                ('haqida', models.CharField(blank=True, max_length=100, null=True)),
                ('yoshi', models.IntegerField(blank=True, null=True)),
                ('rasmi', models.ImageField(blank=True, null=True, upload_to='barber_image/')),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.barber')),
            ],
            options={
                'unique_together': {('barber', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=3, max_digits=15)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='client.barber')),
            ],
            options={
                'unique_together': {('barber', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.barber')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='client.date')),
            ],
            options={
                'unique_together': {('barber', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=100, null=True)),
                ('familiya', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('telefon', models.CharField(max_length=100, null=True)),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='client.barber')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sana', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.date')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.level')),
                ('vaqt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.time')),
            ],
        ),
    ]
