# Generated by Django 5.2 on 2025-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites_name', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('url1', models.CharField(blank=True, max_length=100, null=True)),
                ('url2', models.CharField(blank=True, max_length=100, null=True)),
                ('url3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('yt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
